export const intData = [
  {
    economy: "India",
    regFramework: 65,
    publicService: 56,
    operEfficiency: 45,
    score: 72,
    Region: "South Asia",
    IncomeGroup: "5000",
  },
  {
    economy: "China",
    regFramework: 65,
    publicService: 56,
    operEfficiency: 45,
    score: 78,
    Region: "Central Asia",
    IncomeGroup: "7000",
  },
  {
    economy: "USA",
    regFramework: 67,
    publicService: 65,
    operEfficiency: 54,
    score: 80,
    Region: "America",
    IncomeGroup: "15000",
  },
  {
    economy: "Zimbawe",
    regFramework: 76,
    publicService: 56,
    operEfficiency: 51,
    score: 24,
    Region: "Africa",
    IncomeGroup: "1348",
  },
  {
    economy: "Kenya",
    regFramework: 13,
    publicService: 45,
    operEfficiency: 30,
    score: 27,
    Region: "Africa",
    IncomeGroup: "2033",
  },
  {
    economy: "France",
    regFramework: 55,
    publicService: 68,
    operEfficiency: 60,
    score: 53,
    Region: "Europe",
    IncomeGroup: "17000",
  },
];
